// GENERATED BY HAND (no build_runner needed here)

part of 'photo_info.dart';

class PhotoInfoAdapter extends TypeAdapter<PhotoInfo> {
  @override
  final int typeId = 11;

  @override
  PhotoInfo read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return PhotoInfo(
      id: fields[0] as String,
      path: fields[1] as String,
      width: fields[2] as int,
      height: fields[3] as int,
      thumbPath: fields[4] as String,
    );
  }

  @override
  void write(BinaryWriter writer, PhotoInfo obj) {
    writer
      ..writeByte(5)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.path)
      ..writeByte(2)
      ..write(obj.width)
      ..writeByte(3)
      ..write(obj.height)
      ..writeByte(4)
      ..write(obj.thumbPath);
  }
}
